### ISSUE TITLE
cannot stat 'cap.png'

### ISSUE THREAD

**Issue by ajlennon** [MatthewCroughan/NixThePlanet#28]
Trying to run up the Hackintosh again and for some reason it decided to do a completel rebuild

And now it's giving me

![image](https://github.com/MatthewCroughan/NixThePlanet/assets/1537834/25aabc55-78cf-4fbb-9071-91112ca6e568)

**Comment by MatthewCroughan** [comment]
> for some reason it decided to do a complete rebuild

That's because you used a newer release of this repo, which uses a newer qemu for the build, and for the runtime. I don't see any hashes in your flake URL. Use the git commit hash of the version you want, and then a rebuild won't occur. The build didn't fail, and cap.png not being found isn't an error in the build, it's a log message. You posted only one line of the log, there are many log lines as part of the build, but they aren't being shown here.

**Comment by MatthewCroughan** [comment]
Since you didn't store the git hash, or write a nix expression, I can only guess at the last time you ran the flake, but try `fa0c25456185df578f29b8fe878648ed4620eb55` like `nix run github:matthewcroughan/nixtheplanet/fa0c25456185df578f29b8fe878648ed4620eb55#macos-ventura`

**Comment by ajlennon** [comment]
That doesn't sound right to me. I ran it up last night using the command in the readme and it mostly used what was already built.

Then I exited it and ran it up again and it started doing a complete build.

And there's not been a commit so I don't see why it woul rebuilding.

Good to know the "file not found" error isn't an error...

**Comment by ajlennon** [comment]
It's popping up with something or other "CRITICAL" but I can't see what it's saying. `--debug` doesn't seem to help. How do I show the logs?

**Comment by MatthewCroughan** [comment]
Solved this out of band on Telegram. For completeness of the issue, showing logs is done with `-L` in Nix. The `cap.png` error in the log was a symptom of the build hanging, due to `/dev/kvm` not being accessible by the user running Nix, on the Ubuntu machine this was being ran on.

**Comment by ajlennon** [comment]
Thanks for the help!
